admin_login=(admin);
admin_pass=(50380500c7fd1b6b2adc205a09c8d598);

host=(127.0.0.1);
database=(fp_site1);
user=(fp_site1);
password=(4QPxIBlym7);

sitename_1=(Flowers Delivery FLOR People);
sitename_2=(Flowers Delivery «FLOR People»);
admin_email=(info@florpeople.com);
notify_email=(info@florpeople.com);
phone=((093) 000-88-03);
phone_2=((093) 777-05-50);
skype=(skype_name);

social_fb=(https://www.facebook.com/FlorPeople);
social_ok=(http://ok.ru/);
social_vk=(https://vk.com/flor_people);
social_gp=(https://plus.google.com/);
social_tw=(http://instagram.com/flor_people);
social_ins=(http://instagram.com/flor_people);

products_per_page=(200);
products_per_main_page=(10);
products_per_admin_page=(15);
max_order_items=(50);
item_unit=(шт.);

water_mark_img=();
water_mark_position=(2);
water_mark_opacity=(80);

admin_orders_default_view=(block);

sale_plan=(25000);

photo_price=(30);
card_price=(50);

usd=(28);
